# List of hyperparameters stored in a yaml file for easy access and modifying.
hyperparameters:
  batch_size: 32
  epochs: 100

  input_shape: [3, 224, 224]
  output_classes: 2
  dropout: 0.25

  linear_1: 256
  linear_2: 128
  linear_3: 64

  # hyperparameters for convolution layers - format: (out, kernel_size, stride, padding)
  conv1: [64, 3, 1, 1]
  conv2: [128, 3, 1, 1]
  conv3: [256, 3, 1, 1]
  conv4: [256, 3, 1, 1]
  conv5: [128, 3, 1, 1]

  # learning rate scheduler - format: (mode, factor, patience)
  lr_scheduler: ['min', 0.5, 10]

